import { Download, FileText, Mail, TimerReset } from "lucide-react";
import { SnapshotTable } from "../../components/tables/SnapshotTable.jsx";
import { StatusPill } from "../../components/ui/StatusPill.jsx";

const ceoReports = ["Executive Summary", "Financial Performance", "Branch Performance", "Network Risk", "Board Pack", "Dialysis Contribution"];
const cooReports = ["Daily Ops Command", "Capacity & Flow", "Discharge Pipeline", "Dialysis Operations", "Equipment Readiness", "Pharmacy Stock"];

const exportRows = [
  ["Daily Ops Command", "Elena Morris", "Today 08:00", "Daily", { value: "Ready", pill: true }],
  ["Capacity & Flow", "System", "Yesterday", "Daily", { value: "Ready", pill: true }],
  ["Dialysis Operations", "Nisha Varma", "2 days ago", "Weekly", { value: "Scheduled", pill: true }],
  ["Branch Performance", "Finance PMO", "3 days ago", "Weekly", { value: "Ready", pill: true }],
];

export function ReportsPage({ role }) {
  const reports = role === "COO" ? cooReports : ceoReports;

  return (
    <section className="route-page">
      <div className="route-card-grid route-card-grid--three">
        {reports.map((report, index) => (
          <article className="ceo-scan-card route-report-card" key={report}>
            <div className="route-card-title">
              <FileText size={18} />
              <span>{report}</span>
              <StatusPill status={index < 3 ? "Ready" : "Scheduled"} />
            </div>
            <p>{role === "COO" ? "Operational view with owner, blocker, and same-day action context." : "Executive view with trends, risk movement, and network summary."}</p>
            <div className="route-report-actions">
              <button type="button">
                <Download size={15} /> Export
              </button>
              <button type="button">
                <Mail size={15} /> Send
              </button>
              <button type="button">
                <TimerReset size={15} /> Schedule
              </button>
            </div>
          </article>
        ))}
      </div>

      <SnapshotTable
        headers={["Report", "Generated by", "Generated", "Schedule", "Status"]}
        rows={exportRows}
        summary="Last 30 days."
        title="Recent Exports & Scheduled Reports"
      />
    </section>
  );
}
